project:
  type: website

website:
  title: "Applied Regression with R"
  repo-url: https://github.com/rpruim/applied-regression-tutorials
  repo-actions: [edit, issue]
  page-navigation: true
  sidebar: 
    style: "docked"
    collapse-level: 3
    contents: 
      - href: index.qmd
      - section: R Basics
        contents:
          - href: r-install.qmd
            text: "Install R/RStudio"
          - href: r-basics.qmd
            text: "R Basics"
          - href: quarto-how-to.qmd
            text: "Using Quarto"
          - href: quarto-math.qmd
            text: "Mathematical Notation"
          - href: quarto-results.qmd
            text: "R Results in Text"
      - section: Visualization
        contents: 
          - href: graphics-design.qmd
            text: "Designing Data Visualizations"
          - href: graphics-choose.qmd
            text: "Choosing a Graph Type"
          - href: graphics-code.qmd
            text: "Code Examples"
      - section: Linear Models
        contents: 
          - href: lm-plan.qmd
            text: "Model Planning for Inference"
          - href: lm-fit.qmd
            text: "Model Fitting and Equation"
          - href: lm-assess.qmd
            text: "Model Assessment"
          - href: lm-interp.qmd
            text: "Interpretation and Inference"
          - href: lm-interp-more.qmd
            text: "More Inference"
  navbar:
    search: true
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: litera
    css: styles.css
    # css: [include/webex.css, styles.css]
    # include-after-body: include/webex.js
    toc: true

editor: source